#!/bin/bash
# fixlink neru-icon-classic-theme-2.7
#

link_prepare() {
    mkdir -p neru-classic-light/32x32/apps
    mkdir -p neru-classic-light/32x32/mimetypes
    ln -s home-mdk.svg neru-classic-light/32x32/apps/go-home.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/graphics-viewer-document.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/org.gnome.Evince.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/xpdf9.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/accessories-document-viewer.svg
    ln -s qv4l2.svg neru-classic-light/32x32/apps/qvidcap.svg
    ln -s usb-creator.svg neru-classic-light/32x32/apps/mintstick.svg
    ln -s filelight.svg neru-classic-light/32x32/apps/org.gnome.DiskUtility.svg
    ln -s ark.svg neru-classic-light/32x32/apps/org.gnome.ArchiveManager.svg
    ln -s preferences-system-privacy.svg neru-classic-light/32x32/apps/org.gnome.seahorse.Application.svg
    ln -s applications-fonts.svg neru-classic-light/32x32/apps/org.gnome.font-viewer.svg
    ln -s applications-multimedia.svg neru-classic-light/32x32/apps/gmtpicon.svg
    ln -s fontforge.svg neru-classic-light/32x32/apps/org.fontforge.FontForge.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/Insight-FileManager.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/WorkerIcon48.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/file-manager.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/filerunner.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/kfm.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/nautilus-actions-config-tool.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/redhat-filemanager.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/user-file-manager.svg
    ln -s utilities-terminal.svg neru-classic-light/32x32/apps/org.gnome.Terminal.svg
    ln -s preferences-desktop-color.svg neru-classic-light/32x32/apps/xfce4-color-settings.svg
    ln -s wps-office-wpsmain.svg neru-classic-light/32x32/apps/wps-office2019-wpsmain.svg
    #ln -s wps-office-wpsmain.svg neru-classic-light/32x32/apps/wps-office2019-kprometheus.svg
    ln -s wps-office-wppmain.svg neru-classic-light/32x32/apps/wps-office2019-wppmain.svg
    ln -s preferences-desktop-color.svg neru-classic-light/32x32/apps/package_graphics.svg
    ln -s electron.svg neru-classic-light/32x32/apps/electron4.svg
    ln -s electron.svg neru-classic-light/32x32/apps/electron6.svg
    ln -s wps-office-wpsmain.svg neru-classic-light/32x32/apps/com.wps.Office2019.wpsmain.svg
    ln -s wps-office-wppmain.svg neru-classic-light/32x32/apps/com.wps.Office2019.wppmain.svg
    ln -s wps-office-wpsmain.svg neru-classic-light/32x32/apps/com.wps.Office.wpsmain.svg
    ln -s wps-office-wppmain.svg neru-classic-light/32x32/apps/com.wps.Office.wppmain.svg
    ln -s wps-office-etmain.svg neru-classic-light/32x32/apps/wps-office2019-etmain.svg
    ln -sf preferences-desktop-multimedia.svg neru-classic-light/32x32/apps/redhat-sound_video.svg

    ln -s wps-office-pdfmain.svg neru-classic-light/32x32/apps/wps-office2019-pdfmain.svg
    ln -s wps-office-pdfmain.svg neru-classic-light/32x32/apps/com.wps.Office2019.pdfmain.svg
    ln -s wps-office-pdfmain.svg neru-classic-light/32x32/apps/com.wps.Office.pdfmain.svg
    ln -s distributor-logo-archlinux.svg neru-classic-light/32x32/apps/kalu.svg
    ln -s supertux.svg neru-classic-light/32x32/apps/supertux2.svg

    rm -f neru-classic-light/32x32/apps/pick-colour-picker.svg
    rm -f neru-classic-light/32x32/apps/xfce-system.svg

    ln -s ardour.svg neru-classic-light/32x32/apps/Ardour-Ardour_5.12.0.svg
    ln -s kipi-panorama.svg neru-classic-light/32x32/apps/Panini.svg
    ln -s scantailor.svg neru-classic-light/32x32/apps/ScanTailor.svg
    ln -s teamviewer.svg neru-classic-light/32x32/apps/TeamViewer.svg
    ln -s preferences-desktop-emoticons.svg neru-classic-light/32x32/apps/amor.svg
    ln -s rednotebook.svg neru-classic-light/32x32/apps/app.rednotebook.RedNotebook.svg
    ln -s brackets-electron.svg neru-classic-light/32x32/apps/appimagekit-brackets-electron.svg
    ln -s clipgrab.svg neru-classic-light/32x32/apps/appimagekit-clipgrab.svg
    ln -s emacs.svg neru-classic-light/32x32/apps/appimagekit-emacs.svg
    ln -s franz.svg neru-classic-light/32x32/apps/appimagekit-franz.svg
    ln -s gmail.svg neru-classic-light/32x32/apps/appimagekit-gmail-desktop.svg
    ln -s mellowplayer.svg neru-classic-light/32x32/apps/appimagekit-mellowplayer.svg
    ln -s museeks.svg neru-classic-light/32x32/apps/appimagekit-museeks.svg
    ln -s keepassxc.svg neru-classic-light/32x32/apps/appimagekit-org.keepassxc.KeePassXC.svg
    ln -s org.olivevideoeditor.Olive.svg neru-classic-light/32x32/apps/appimagekit-org.olivevideoeditor.Olive.svg
    ln -s rambox.svg neru-classic-light/32x32/apps/appimagekit-rambox.svg
    ln -s stacer.svg neru-classic-light/32x32/apps/appimagekit-stacer.svg
    ln -s supertux.svg neru-classic-light/32x32/apps/appimagekit-supertux2.svg
    ln -s synfig_icon.svg neru-classic-light/32x32/apps/appimagekit-synfigstudio.svg
    ln -s wechat.svg neru-classic-light/32x32/apps/appimagekit-wewechat.svg
    ln -s wire.svg neru-classic-light/32x32/apps/appimagekit-wire-desktop.svg
    ln -s java.svg neru-classic-light/32x32/apps/applications-java.svg
    ln -s tuxguitar.svg neru-classic-light/32x32/apps/ar.com.tuxguitar.TuxGuitar.svg
    ln -s boinc.svg neru-classic-light/32x32/apps/boinc-manager.svg
    ln -s accessories-text-editor.svg neru-classic-light/32x32/apps/bottles_notepad.svg
    ln -s wine-uninstaller.svg neru-classic-light/32x32/apps/bottles_wine-uninstaller.svg
    ln -s winecfg.svg neru-classic-light/32x32/apps/bottles_wine-winecfg.svg
    ln -s wine.svg neru-classic-light/32x32/apps/bottles_wine.svg
    ln -s winetricks.svg neru-classic-light/32x32/apps/bottles_winetricks.svg
    ln -s brave.svg neru-classic-light/32x32/apps/brave-browser-beta.svg
    ln -s brave.svg neru-classic-light/32x32/apps/brave-browser.svg
    ln -s fceux.svg neru-classic-light/32x32/apps/ca._0ldsk00l.Nestopia.svg
    ln -s dconf-editor.svg neru-classic-light/32x32/apps/ca.desrt.dconf-editor.svg
    ln -s accessories-ebook-reader.svg neru-classic-light/32x32/apps/calibre.svg
    ln -s arduino.svg neru-classic-light/32x32/apps/cc.arduino.arduinoide.svg
    ln -s rocketchat.svg neru-classic-light/32x32/apps/chat.rocket.RocketChat.svg
    ln -s chess.svg neru-classic-light/32x32/apps/chessx.svg
    ln -s geogebra.svg neru-classic-light/32x32/apps/chrome-bnbaboaihhkjoaolfnfoablhllahjnee-Default.svg
    ln -s whatsapp.svg neru-classic-light/32x32/apps/chrome-bommmmpbplimfmebiadkflfgbgejahgm-Default.svg
    ln -s evernote.svg neru-classic-light/32x32/apps/chrome-lbfehkoinhhcknnbdgnnmjhiladcgbol-Default.svg
    ln -s devdocs.svg neru-classic-light/32x32/apps/chrome-mnfehgbmkapmjnhcnbodoamcioleeooe-Default.svg
    ln -s showtime.svg neru-classic-light/32x32/apps/chrome-nmgfcbigejokjgholnnnipegblickgnp-Default.svg
    ln -s granatier.svg neru-classic-light/32x32/apps/clanbomber.svg
    ln -s kipi-logo.svg neru-classic-light/32x32/apps/colors.svg
    ln -s abiword.svg neru-classic-light/32x32/apps/com.abisource.AbiWord.svg
    ln -s flash.svg neru-classic-light/32x32/apps/com.adobe.Flash-Player-Projector.svg
    ln -s gitkraken.svg neru-classic-light/32x32/apps/com.axosoft.GitKraken.svg
    ln -s calibre-ebook-edit.svg neru-classic-light/32x32/apps/com.calibre_ebook.calibre.ebook_edit.svg
    ln -s calibre-viewer.svg neru-classic-light/32x32/apps/com.calibre_ebook.calibre.ebook_viewer.svg
    ln -s calibre-viewer.svg neru-classic-light/32x32/apps/com.calibre_ebook.calibre.lrfviewer.svg
    ln -s accessories-ebook-reader.svg neru-classic-light/32x32/apps/com.calibre_ebook.calibre.svg
    ln -s office-calendar.svg neru-classic-light/32x32/apps/com.deepin.Calendar.svg
    ln -s multimedia-photo-viewer.svg neru-classic-light/32x32/apps/com.deepin.ImageViewer.svg
    ln -s juk.svg neru-classic-light/32x32/apps/com.deepin.Music.svg
    ln -s applets-screenshooter.svg neru-classic-light/32x32/apps/com.deepin.ScreenShot.svg
    ln -s sound-recorder.svg neru-classic-light/32x32/apps/com.deepin.VoiceRecorder.svg
    ln -s dosbox.svg neru-classic-light/32x32/apps/com.dosbox.DOSBox.svg
    ln -s dropbox.svg neru-classic-light/32x32/apps/com.dropbox.Client.svg
    ln -s mendeley-desktop.svg neru-classic-light/32x32/apps/com.elsevier.MendeleyDesktop.svg
    ln -s postman.svg neru-classic-light/32x32/apps/com.getpostman.Postman.svg
    ln -s flacon.svg neru-classic-light/32x32/apps/com.github.Flacon.svg
    ln -s youtube-dl.svg neru-classic-light/32x32/apps/com.github.JannikHv.Gydl.svg
    ln -s kipi-logo.svg neru-classic-light/32x32/apps/com.github.PintaProject.Pinta.svg
    ln -s scantailor.svg neru-classic-light/32x32/apps/com.github._4lex4.ScanTailor-Advanced.svg
    ln -s taxi.svg neru-classic-light/32x32/apps/com.github.alecaddd.taxi.svg
    ln -s usb-creator.svg neru-classic-light/32x32/apps/com.github.artemanufrij.imageburner.svg
    ln -s simplescreenrecorder.svg neru-classic-light/32x32/apps/com.github.artemanufrij.screencast.svg
    ln -s bookworm.svg neru-classic-light/32x32/apps/com.github.babluboy.bookworm.svg
    ln -s kdeconnect.svg neru-classic-light/32x32/apps/com.github.bajoja.indicator-kdeconnect.svg
    ln -s gnome-twofactorauth.svg neru-classic-light/32x32/apps/com.github.bilelmoussaoui.Authenticator.svg
    ln -s weather.svg neru-classic-light/32x32/apps/com.github.bitseater.weather.svg
    ln -s money-manager-ex.svg neru-classic-light/32x32/apps/com.github.brandonlujan.exchange.svg
    ln -s audiobook.svg neru-classic-light/32x32/apps/com.github.geigi.cozy.svg
    ln -s korganizer.svg neru-classic-light/32x32/apps/com.github.georgekap1an.chores.svg
    ln -s copyq.svg neru-classic-light/32x32/apps/com.github.hluk.copyq.svg
    ln -s accessories-dictionary.svg neru-classic-light/32x32/apps/com.github.lainsce.palaura.svg
    ln -s tor.svg neru-classic-light/32x32/apps/com.github.micahflee.torbrowser-launcher.svg
    ln -s ksudoku.svg neru-classic-light/32x32/apps/com.github.parnold-x.sudoku.svg
    ln -s lokalize.svg neru-classic-light/32x32/apps/com.github.rapidfingers.translator.svg
    ln -s akregator.svg neru-classic-light/32x32/apps/com.github.rssguard.svg
    ln -s preferences-desktop-icons.svg neru-classic-light/32x32/apps/com.github.santileortiz.iconoscope.svg
    ln -s system-error.svg neru-classic-light/32x32/apps/com.github.timecraft.notifier.svg
    ln -s pulseeffects.svg neru-classic-light/32x32/apps/com.github.wwmm.pulseeffects.svg
    ln -s xournal.svg neru-classic-light/32x32/apps/com.github.xournalpp.xournalpp.svg
    ln -s haguichi.svg neru-classic-light/32x32/apps/com.github.ztefn.haguichi.svg
    ln -s androidstudio.svg neru-classic-light/32x32/apps/com.google.AndroidStudio.svg
    ln -s google-play-music-desktop-player.svg neru-classic-light/32x32/apps/com.googleplaymusicdesktopplayer.GPMDP.svg
    ln -s skanlite.svg neru-classic-light/32x32/apps/com.hamrick.VueScan.svg
    ln -s datagrip.svg neru-classic-light/32x32/apps/com.jetbrains.DataGrip.svg
    ln -s intellij.svg neru-classic-light/32x32/apps/com.jetbrains.IntelliJ-IDEA-Community.svg
    ln -s intellij.svg neru-classic-light/32x32/apps/com.jetbrains.IntelliJ-IDEA-Ultimate.svg
    ln -s phpstorm.svg neru-classic-light/32x32/apps/com.jetbrains.PhpStorm.svg
    ln -s pycharm.svg neru-classic-light/32x32/apps/com.jetbrains.PyCharm-Community.svg
    ln -s pycharm.svg neru-classic-light/32x32/apps/com.jetbrains.PyCharm-Professional.svg
    ln -s webstorm.svg neru-classic-light/32x32/apps/com.jetbrains.WebStorm.svg
    ln -s league-of-legends.svg neru-classic-light/32x32/apps/com.leagueoflegends.Client.svg
    ln -s makemkv.svg neru-classic-light/32x32/apps/com.makemkv.MakeMKV.svg
    ln -s franz.svg neru-classic-light/32x32/apps/com.meetfranz.Franz.svg
    ln -s minecraft.svg neru-classic-light/32x32/apps/com.mojang.Minecraft.svg
    ln -s netease-cloud-music.svg neru-classic-light/32x32/apps/com.netease.CloudMusic.svg
    ln -s notepadqq.svg neru-classic-light/32x32/apps/com.notepadqq.Notepadqq.svg
    ln -s obs.svg neru-classic-light/32x32/apps/com.obsproject.Studio.svg
    ln -s vidcutter.svg neru-classic-light/32x32/apps/com.ozmartians.VidCutter.svg
    ln -s rawtherapee.svg neru-classic-light/32x32/apps/com.rawtherapee.RawTherapee.svg
    ln -s slack.svg neru-classic-light/32x32/apps/com.slack.Slack.svg
    ln -s sublime-text.svg neru-classic-light/32x32/apps/com.sublimetext.three.svg
    ln -s smartgit.svg neru-classic-light/32x32/apps/com.syntevo.SmartGit.svg
    ln -s teamspeak3.svg neru-classic-light/32x32/apps/com.teamspeak.TeamSpeak.svg
    ln -s transmission.svg neru-classic-light/32x32/apps/com.transmissionbt.Transmission.svg
    ln -s viber.svg neru-classic-light/32x32/apps/com.viber.Viber.svg
    ln -s astromenace.svg neru-classic-light/32x32/apps/com.viewizard.AstroMenace.svg
    ln -s visual-studio-code.svg neru-classic-light/32x32/apps/com.visualstudio.code.svg
    ln -s wire.svg neru-classic-light/32x32/apps/com.wire.WireDesktop.svg
    ln -s wps-office-etmain.svg neru-classic-light/32x32/apps/com.wps.Office.etmain.svg
    ln -s wps-office-etmain.svg neru-classic-light/32x32/apps/com.wps.Office2019.etmain.svg
    ln -s xnretro.svg neru-classic-light/32x32/apps/com.xnview.XnRetro.svg
    ln -s zandronum.svg neru-classic-light/32x32/apps/com.zandronum.Zandronum.svg
    ln -s system-log-out.svg neru-classic-light/32x32/apps/computer-log-out.svg
    ln -s utilities-tweak-tool.svg neru-classic-light/32x32/apps/computersettings.svg
    ln -s preferences-web-browser-cookies.svg neru-classic-light/32x32/apps/cookie.svg
    ln -s preferences-desktop-online-accounts.svg neru-classic-light/32x32/apps/cs-online-accounts.svg
    ln -s ring.svg neru-classic-light/32x32/apps/cx.ring.Ring.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/d3lphin.svg
    ln -s office-calendar.svg neru-classic-light/32x32/apps/dde-calendar.svg
    ln -s accessories-calculator.svg neru-classic-light/32x32/apps/deepin-calculator.svg
    ln -s yast-snapper.svg neru-classic-light/32x32/apps/deepin-clone.svg
    ln -s crossover.svg neru-classic-light/32x32/apps/deepin-crossover.svg
    ln -s accessories-text-editor.svg neru-classic-light/32x32/apps/deepin-editor.svg
    ln -s kfontview.svg neru-classic-light/32x32/apps/deepin-font-installer.svg
    ln -s jockey.svg neru-classic-light/32x32/apps/deepin-graphics-driver-manager.svg
    ln -s ubiquity-kde.svg neru-classic-light/32x32/apps/deepin-installer-oem.svg
    ln -s accessories-notes.svg neru-classic-light/32x32/apps/deepin-note.svg
    ln -s skanlite.svg neru-classic-light/32x32/apps/deepin-scanner.svg
    ln -s applications-utilities.svg neru-classic-light/32x32/apps/deepin-system-monitor.svg
    ln -s devdocs.svg neru-classic-light/32x32/apps/deepin.com.wechat.devtools.svg
    ln -s wechat.svg neru-classic-light/32x32/apps/deepin.com.wechat.svg
    ln -s knemo.svg neru-classic-light/32x32/apps/dhcpcd.svg
    ln -s discord.svg neru-classic-light/32x32/apps/discord-ptb.svg
    ln -s tuxpuck.svg neru-classic-light/32x32/apps/distributor-logo-crux.svg
    ln -s k9-copy.svg neru-classic-light/32x32/apps/dvd95.svg
    ln -s k9-copy.svg neru-classic-light/32x32/apps/dvd9548.svg
    ln -s internet-mail.svg neru-classic-light/32x32/apps/email.svg
    ln -s Encryptr.svg neru-classic-light/32x32/apps/encryptr.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/epdfview.svg
    ln -s kphotoalbum.svg neru-classic-light/32x32/apps/ephoto.svg
    ln -s kmix.svg neru-classic-light/32x32/apps/epulse.svg
    ln -s homebank.svg neru-classic-light/32x32/apps/fr.free.Homebank.svg
    ln -s freecad.svg neru-classic-light/32x32/apps/freecad-daily.svg
    ln -s fritzing.svg neru-classic-light/32x32/apps/fritzing_icon.svg
    ln -s gcompris.svg neru-classic-light/32x32/apps/gcompris-qt.svg
    ln -s disk-usage-analyzer.svg neru-classic-light/32x32/apps/gdmap_icon.svg
    ln -s geogebra.svg neru-classic-light/32x32/apps/geogebra-classic.svg
    ln -s radiotray.svg neru-classic-light/32x32/apps/girl.svg
    ln -s git.svg neru-classic-light/32x32/apps/git-gui.svg
    ln -s jockey.svg neru-classic-light/32x32/apps/glxinfo.svg
    ln -s gmail.svg neru-classic-light/32x32/apps/gmail-desktop.svg
    ln -s applications-utilities.svg neru-classic-light/32x32/apps/gnethogs.svg
    ln -s radiotray.svg neru-classic-light/32x32/apps/gnome-internet-radio-locator.svg
    ln -s latexila.svg neru-classic-light/32x32/apps/gnome-latex.svg
    ln -s system-log-out.svg neru-classic-light/32x32/apps/gnome-logout.svg
    ln -s bluefish.svg neru-classic-light/32x32/apps/gnome-panel-fish.svg
    ln -s xorg.svg neru-classic-light/32x32/apps/gnome-panel-force-quit.svg
    ln -s system-suspend-hibernate.svg neru-classic-light/32x32/apps/gnome-panel-hibernate.svg
    ln -s preferences-desktop-notification-bell.svg neru-classic-light/32x32/apps/gnome-panel-notification-area.svg
    ln -s mate-inhibit-applet.svg neru-classic-light/32x32/apps/gnome-panel-suspend.svg
    ln -s facebook.svg neru-classic-light/32x32/apps/goa-account-facebook.svg
    ln -s lastfm.svg neru-classic-light/32x32/apps/goa-account-lastfm.svg
    ln -s nextcloud.svg neru-classic-light/32x32/apps/goa-account-owncloud.svg
    ln -s pocket.svg neru-classic-light/32x32/apps/goa-account-pocket.svg
    ln -s maps.svg neru-classic-light/32x32/apps/gpxsee.svg
    ln -s kphotoalbum.svg neru-classic-light/32x32/apps/gtkam-camera.svg
    ln -s GP6-icon.svg neru-classic-light/32x32/apps/guitarpro6.svg
    ln -s youtube-dl.svg neru-classic-light/32x32/apps/gydl.svg
    ln -s hydrogen.svg neru-classic-light/32x32/apps/h2-icon.svg
    ln -s rambox.svg neru-classic-light/32x32/apps/hamsket.svg
    ln -s preferences-desktop-icons.svg neru-classic-light/32x32/apps/icons.svg
    ln -s icons.svg neru-classic-light/32x32/apps/iconthemes.svg
    ln -s icq.svg neru-classic-light/32x32/apps/icq_protocol.svg
    ln -s gitter.svg neru-classic-light/32x32/apps/im.gitter.Gitter.svg
    ln -s pidgin.svg neru-classic-light/32x32/apps/im.pidgin.Pidgin.svg
    ln -s riot-web.svg neru-classic-light/32x32/apps/im.riot.Riot.svg
    ln -s war-thunder.svg neru-classic-light/32x32/apps/in.p1x.TanksOfFreedom.svg
    ln -s bibletime.svg neru-classic-light/32x32/apps/info.bibletime.BibleTime.svg
    ln -s mumble.svg neru-classic-light/32x32/apps/info.mumble.Mumble.svg
    ln -s preferences-desktop-gaming.svg neru-classic-light/32x32/apps/input-joystick.svg
    ln -s intellij.svg neru-classic-light/32x32/apps/intellij-idea-ultimate.svg
    ln -s atom.svg neru-classic-light/32x32/apps/io.atom.Atom.svg
    ln -s electron.svg neru-classic-light/32x32/apps/io.atom.electron.BaseApp.svg
    ln -s brackets.svg neru-classic-light/32x32/apps/io.brackets.Brackets.svg
    ln -s dbeaver.svg neru-classic-light/32x32/apps/io.dbeaver.DBeaverCommunity.svg
    ln -s gnome-mpv.svg neru-classic-light/32x32/apps/io.github.Celluloid.svg
    ln -s fontforge.svg neru-classic-light/32x32/apps/io.github.Fontforge.svg
    ln -s gnome-mpv.svg neru-classic-light/32x32/apps/io.github.celluloid_player.Celluloid.svg
    ln -s fmit.svg neru-classic-light/32x32/apps/io.github.gillesdegottex.FMIT.svg
    ln -s flowblade.svg neru-classic-light/32x32/apps/io.github.jliljebl.Flowblade.svg
    ln -s typecatcher.svg neru-classic-light/32x32/apps/io.github.mmstick.FontFinder.svg
    ln -s WMail.svg neru-classic-light/32x32/apps/io.github.openWMail.openWMail.svg
    ln -s utox.svg neru-classic-light/32x32/apps/io.github.qtox.qTox.svg
    ln -s quodlibet.svg neru-classic-light/32x32/apps/io.github.quodlibet.QuodLibet.svg
    ln -s ghostwriter.svg neru-classic-light/32x32/apps/io.github.wereturtle.ghostwriter.svg
    ln -s goodvibes.svg neru-classic-light/32x32/apps/io.gitlab.Goodvibes.svg
    ln -s preferences-desktop-gaming.svg neru-classic-light/32x32/apps/io.gitlab.jstest_gtk.jstest_gtk.svg
    ln -s accessories-calculator.svg neru-classic-light/32x32/apps/io.liri.Calculator.svg
    ln -s accessories-text-editor.svg neru-classic-light/32x32/apps/io.liri.Text.svg
    ln -s lmms.svg neru-classic-light/32x32/apps/io.lmms.LMMS.svg
    ln -s nvim.svg neru-classic-light/32x32/apps/io.neovim.nvim.svg
    ln -s gaupol.svg neru-classic-light/32x32/apps/io.otsaloma.gaupol.svg
    ln -s webtorrent-desktop.svg neru-classic-light/32x32/apps/io.webtorrent.WebTorrent.svg
    ln -s ring.svg neru-classic-light/32x32/apps/jami.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-1.8.0-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-10-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-11-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-12-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-13-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java-14-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java10-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java11-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java12-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java13-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java14-openjdk.svg
    ln -s java.svg neru-classic-light/32x32/apps/java9-openjdk.svg
    ln -s openspades.svg neru-classic-light/32x32/apps/jp.yvt.OpenSpades.svg
    ln -s preferences-system-search.svg neru-classic-light/32x32/apps/kappfinder.svg
    ln -s kate.svg neru-classic-light/32x32/apps/kate2.svg
    ln -s accessories-character-map.svg neru-classic-light/32x32/apps/kcharselect.svg
    ln -s cs-panel.svg neru-classic-light/32x32/apps/kcmkicker.svg
    ln -s vmpk.svg neru-classic-light/32x32/apps/kcmmidi.svg
    ln -s jockey.svg neru-classic-light/32x32/apps/kcmpci.svg
    ln -s yast-hwinfo.svg neru-classic-light/32x32/apps/kcmprocessor.svg
    ln -s yast-sound.svg neru-classic-light/32x32/apps/kcmsound.svg
    ln -s xorg.svg neru-classic-light/32x32/apps/kcmx.svg
    ln -s kipi-logo.svg neru-classic-light/32x32/apps/kcoloredit.svg
    ln -s utilities-tweak-tool.svg neru-classic-light/32x32/apps/kcontrol.svg
    ln -s disk-usage-analyzer.svg neru-classic-light/32x32/apps/kdf.svg
    ln -s mate-panel-drawer.svg neru-classic-light/32x32/apps/kdisknav.svg
    ln -s plasmagik.svg neru-classic-light/32x32/apps/keditbookmarks.svg
    ln -s gargoyle-house.svg neru-classic-light/32x32/apps/kfm_home.svg
    ln -s kid3.svg neru-classic-light/32x32/apps/kid3-qt.svg
    ln -s kipi-logo.svg neru-classic-light/32x32/apps/kipi.svg
    ln -s cups.svg neru-classic-light/32x32/apps/kjobviewer.svg
    ln -s preferences-system-notifications.svg neru-classic-light/32x32/apps/knotify.svg
    ln -s workspace-switcher-left-bottom.svg neru-classic-light/32x32/apps/kpager.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/kpdf.svg
    ln -s preferences-desktop-theme.svg neru-classic-light/32x32/apps/kpersonalizer.svg
    ln -s sound-recorder.svg neru-classic-light/32x32/apps/krec.svg
    ln -s krusader_user.svg neru-classic-light/32x32/apps/krusader_blue.svg
    ln -s krusader_root.svg neru-classic-light/32x32/apps/krusader_red.svg
    ln -s preferences-desktop-emoticons.svg neru-classic-light/32x32/apps/ksmiletris.svg
    ln -s preferences-system-splash.svg neru-classic-light/32x32/apps/ksplash.svg
    ln -s disk-usage-analyzer.svg neru-classic-light/32x32/apps/kwikdisk.svg
    ln -s preferences-system-login.svg neru-classic-light/32x32/apps/launch.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreoffice6.2-main.svg
    ln -s libreoffice-base.svg neru-classic-light/32x32/apps/libreoffice6.3-base.svg
    ln -s libreoffice-calc.svg neru-classic-light/32x32/apps/libreoffice6.3-calc.svg
    ln -s libreoffice-draw.svg neru-classic-light/32x32/apps/libreoffice6.3-draw.svg
    ln -s libreoffice-impress.svg neru-classic-light/32x32/apps/libreoffice6.3-impress.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreoffice6.3-main.svg
    ln -s libreoffice-math.svg neru-classic-light/32x32/apps/libreoffice6.3-math.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreoffice6.3-startcenter.svg
    ln -s libreoffice-writer.svg neru-classic-light/32x32/apps/libreoffice6.3-writer.svg
    ln -s libreoffice-base.svg neru-classic-light/32x32/apps/libreofficedev6.0-base.svg
    ln -s libreoffice-calc.svg neru-classic-light/32x32/apps/libreofficedev6.0-calc.svg
    ln -s libreoffice-draw.svg neru-classic-light/32x32/apps/libreofficedev6.0-draw.svg
    ln -s libreoffice-impress.svg neru-classic-light/32x32/apps/libreofficedev6.0-impress.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreofficedev6.0-main.svg
    ln -s libreoffice-math.svg neru-classic-light/32x32/apps/libreofficedev6.0-math.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreofficedev6.0-startcenter.svg
    ln -s libreoffice-writer.svg neru-classic-light/32x32/apps/libreofficedev6.0-writer.svg
    ln -s libreoffice-base.svg neru-classic-light/32x32/apps/libreofficedev6.1-base.svg
    ln -s libreoffice-calc.svg neru-classic-light/32x32/apps/libreofficedev6.1-calc.svg
    ln -s libreoffice-draw.svg neru-classic-light/32x32/apps/libreofficedev6.1-draw.svg
    ln -s libreoffice-impress.svg neru-classic-light/32x32/apps/libreofficedev6.1-impress.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreofficedev6.1-main.svg
    ln -s libreoffice-math.svg neru-classic-light/32x32/apps/libreofficedev6.1-math.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/libreofficedev6.1-startcenter.svg
    ln -s libreoffice-writer.svg neru-classic-light/32x32/apps/libreofficedev6.1-writer.svg
    ln -s preferences-desktop-theme.svg neru-classic-light/32x32/apps/lookswitcher.svg
    ln -s jockey.svg neru-classic-light/32x32/apps/lshw.svg
    ln -s disk-utility.svg neru-classic-light/32x32/apps/matepalimpsest.svg
    ln -s syncthing-gtk.svg neru-classic-light/32x32/apps/me.kozec.syncthingtk.svg
    ln -s minecraft.svg neru-classic-light/32x32/apps/minecraft-launcher.svg
    ln -s utilities-x-terminal.svg neru-classic-light/32x32/apps/mini.xterm.svg
    ln -s preferences-desktop-keyboard-shortcuts.svg neru-classic-light/32x32/apps/mintlocale-im.svg
    ln -s system-error.svg neru-classic-light/32x32/apps/mintreport.svg
    ln -s password-manager.svg neru-classic-light/32x32/apps/mintsources-keys.svg
    ln -s muon.svg neru-classic-light/32x32/apps/mintupdate-release-upgrade.svg
    ln -s skype.svg neru-classic-light/32x32/apps/ms-skype.svg
    ln -s applications-multimedia.svg neru-classic-light/32x32/apps/multimedia.svg
    ln -s knemo.svg neru-classic-light/32x32/apps/mx-broadcom-manager.svg
    ln -s preferences-system-time.svg neru-classic-light/32x32/apps/mx-clocky.svg
    ln -s preferences-system-search.svg neru-classic-light/32x32/apps/mx-findshares.svg
    ln -s kmenuedit.svg neru-classic-light/32x32/apps/mx-menu-editor.svg
    ln -s kmix.svg neru-classic-light/32x32/apps/mx-system-sounds.svg
    ln -s preferences-system-time.svg neru-classic-light/32x32/apps/mx-timeset-gui-icon.svg
    ln -s usb-creator.svg neru-classic-light/32x32/apps/mx-usb-unmounter.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/mx-viewer.svg
    ln -s anki.svg neru-classic-light/32x32/apps/net.ankiweb.Anki.svg
    ln -s ring.svg neru-classic-light/32x32/apps/net.jami.Jami.svg
    ln -s mkvinfo.svg neru-classic-light/32x32/apps/net.mediaarea.MediaInfo.svg
    ln -s poedit.svg neru-classic-light/32x32/apps/net.poedit.Poedit.svg
    ln -s redeclipse.svg neru-classic-light/32x32/apps/net.redeclipse.RedEclipse.svg
    ln -s scribus.svg neru-classic-light/32x32/apps/net.scribus.Scribus.svg
    ln -s fuse.svg neru-classic-light/32x32/apps/net.sf.fuse_emulator.svg
    ln -s nootka.svg neru-classic-light/32x32/apps/net.sf.nootka.svg
    ln -s chess.svg neru-classic-light/32x32/apps/net.sourceforge.Chessx.svg
    ln -s klavaro.svg neru-classic-light/32x32/apps/net.sourceforge.Klavaro.svg
    ln -s lifeograph.svg neru-classic-light/32x32/apps/net.sourceforge.Lifeograph.svg
    ln -s vmpk.svg neru-classic-light/32x32/apps/net.sourceforge.VMPK.svg
    ln -s xournal.svg neru-classic-light/32x32/apps/net.sourceforge.xournal.svg
    ln -s warzone2100.svg neru-classic-light/32x32/apps/net.wz2100.wz2100.svg
    ln -s xmind.svg neru-classic-light/32x32/apps/net.xmind.XMind8.svg
    ln -s xmind.svg neru-classic-light/32x32/apps/net.xmind.ZEN.svg
    ln -s standard-notes.svg neru-classic-light/32x32/apps/notes.svg
    ln -s nvidia.svg neru-classic-light/32x32/apps/nvidia-ddm-mx.svg
    ln -s java.svg neru-classic-light/32x32/apps/openjdk-10.svg
    ln -s java.svg neru-classic-light/32x32/apps/openjdk-11.svg
    ln -s java.svg neru-classic-light/32x32/apps/openjdk-9.svg
    ln -s cups.svg neru-classic-light/32x32/apps/openoffice4-printeradmin.svg
    ln -s java.svg neru-classic-light/32x32/apps/oracle_java9.svg
    ln -s netbeans.svg neru-classic-light/32x32/apps/org.apache.netbeans.svg
    ln -s avidemux.svg neru-classic-light/32x32/apps/org.avidemux.Avidemux.svg
    ln -s bitcoin.svg neru-classic-light/32x32/apps/org.bitcoincore.bitcoin-qt.svg
    ln -s internet-mail.svg neru-classic-light/32x32/apps/org.claws_mail.Claws-Mail.svg
    ln -s clementine.svg neru-classic-light/32x32/apps/org.clementine_player.Clementine.svg
    ln -s codeblocks.svg neru-classic-light/32x32/apps/org.codeblocks.codeblocks.svg
    ln -s electrum.svg neru-classic-light/32x32/apps/org.electrum.electrum.svg
    ln -s mist.svg neru-classic-light/32x32/apps/org.ethereum.Mist.svg
    ln -s mediawriter.svg neru-classic-light/32x32/apps/org.fedoraproject.MediaWriter.svg
    ln -s filezilla.svg neru-classic-light/32x32/apps/org.filezillaproject.Filezilla.svg
    ln -s freecad.svg neru-classic-light/32x32/apps/org.freecadweb.FreeCAD.svg
    ln -s freeciv-client.svg neru-classic-light/32x32/apps/org.freeciv.Freeciv.svg
    ln -s jockey.svg neru-classic-light/32x32/apps/org.freedesktop.GlxInfo.svg
    ln -s freefilesync.svg neru-classic-light/32x32/apps/org.freefilesync.FreeFileSync.svg
    ln -s fritzing.svg neru-classic-light/32x32/apps/org.fritzing.Fritzing.svg
    ln -s gajim.svg neru-classic-light/32x32/apps/org.gajim.Gajim.svg
    ln -s geany.svg neru-classic-light/32x32/apps/org.geany.Geany.svg
    ln -s gimp.svg neru-classic-light/32x32/apps/org.gimp.GIMP.svg
    ln -s kpatience.svg neru-classic-light/32x32/apps/org.gnome.Aisleriot.svg
    ln -s gnome-boxes.svg neru-classic-light/32x32/apps/org.gnome.Boxes.svg
    ln -s accessories-calculator.svg neru-classic-light/32x32/apps/org.gnome.Calculator.svg
    ln -s accessories-character-map.svg neru-classic-light/32x32/apps/org.gnome.Characters.svg
    ln -s chess.svg neru-classic-light/32x32/apps/org.gnome.Chess.svg
    ln -s preferences-desktop-color.svg neru-classic-light/32x32/apps/org.gnome.ColorViewer.svg
    ln -s devhelp.svg neru-classic-light/32x32/apps/org.gnome.Devhelp.svg
    ln -s accessories-dictionary.svg neru-classic-light/32x32/apps/org.gnome.Dictionary.svg
    ln -s evolution.svg neru-classic-light/32x32/apps/org.gnome.Evolution.svg
    ln -s pcbcalculator.svg neru-classic-light/32x32/apps/org.gnome.Genius.svg
    ln -s glade.svg neru-classic-light/32x32/apps/org.gnome.Glade.svg
    ln -s accessories-notes.svg neru-classic-light/32x32/apps/org.gnome.Gnote.svg
    ln -s gnome-klotski.svg neru-classic-light/32x32/apps/org.gnome.Klotski.svg
    ln -s lightsoff.svg neru-classic-light/32x32/apps/org.gnome.LightsOff.svg
    ln -s utilities-log-viewer.svg neru-classic-light/32x32/apps/org.gnome.Logs.svg
    ln -s kmines.svg neru-classic-light/32x32/apps/org.gnome.Mines.svg
    ln -s usb-creator.svg neru-classic-light/32x32/apps/org.gnome.MultiWriter.svg
    ln -s accessories-notes.svg neru-classic-light/32x32/apps/org.gnome.Notes.svg
    ln -s ocrfeeder.svg neru-classic-light/32x32/apps/org.gnome.OCRFeeder.svg
    ln -s quadrapassel.svg neru-classic-light/32x32/apps/org.gnome.Quadrapassel.svg
    ln -s kreversi.svg neru-classic-light/32x32/apps/org.gnome.Reversi.svg
    ln -s rhythmbox.svg neru-classic-light/32x32/apps/org.gnome.Rhythmbox3.svg
    ln -s gnome-robots.svg neru-classic-light/32x32/apps/org.gnome.Robots.svg
    ln -s applets-screenshooter.svg neru-classic-light/32x32/apps/org.gnome.Screenshot.svg
    ln -s utilities-tweak-tool.svg neru-classic-light/32x32/apps/org.gnome.Settings.svg
    ln -s kdeconnect.svg neru-classic-light/32x32/apps/org.gnome.Shell.Extensions.GSConnect.svg
    ln -s multimedia-photo-manager.svg neru-classic-light/32x32/apps/org.gnome.Shotwell.svg
    ln -s gnome-sound-recorder.svg neru-classic-light/32x32/apps/org.gnome.SoundRecorder.svg
    ln -s ksudoku.svg neru-classic-light/32x32/apps/org.gnome.Sudoku.svg
    ln -s swell-foop.svg neru-classic-light/32x32/apps/org.gnome.SwellFoop.svg
    ln -s kronometer.svg neru-classic-light/32x32/apps/org.gnome.Sysprof.svg
    ln -s kjumpingcube.svg neru-classic-light/32x32/apps/org.gnome.Tali.svg
    ln -s gnome-taquin.svg neru-classic-light/32x32/apps/org.gnome.Taquin.svg
    ln -s gnome-tetravex.svg neru-classic-light/32x32/apps/org.gnome.Tetravex.svg
    ln -s accessories-notes.svg neru-classic-light/32x32/apps/org.gnome.Tomboy.svg
    ln -s gnome-2048.svg neru-classic-light/32x32/apps/org.gnome.TwentyFortyEight.svg
    ln -s help-browser.svg neru-classic-light/32x32/apps/org.gnome.Yelp.svg
    ln -s disk-usage-analyzer.svg neru-classic-light/32x32/apps/org.gnome.baobab.svg
    ln -s chess.svg neru-classic-light/32x32/apps/org.gnome.chess.svg
    ln -s accessories-text-editor.svg neru-classic-light/32x32/apps/org.gnome.gedit.svg
    ln -s glabels-3.0.svg neru-classic-light/32x32/apps/org.gnome.glabels-3.svg
    ln -s qgo.svg neru-classic-light/32x32/apps/org.gnome.iagno.svg
    ln -s meld.svg neru-classic-light/32x32/apps/org.gnome.meld.svg
    ln -s quadrapassel.svg neru-classic-light/32x32/apps/org.gnome.quadrapassel.svg
    ln -s gnome-tetravex.svg neru-classic-light/32x32/apps/org.gnome.tetravex.svg
    ln -s gnome-tweak-tool.svg neru-classic-light/32x32/apps/org.gnome.tweaks.svg
    ln -s emacs.svg neru-classic-light/32x32/apps/org.gnu.emacs.svg
    ln -s godot.svg neru-classic-light/32x32/apps/org.godotengine.Godot.svg
    ln -s focuswriter.svg neru-classic-light/32x32/apps/org.gottcode.FocusWriter.svg
    ln -s gpodder.svg neru-classic-light/32x32/apps/org.gpodder.gpodder.svg
    ln -s hedgewars.svg neru-classic-light/32x32/apps/org.hedgewars.Hedgewars.svg
    ln -s hydrogen.svg neru-classic-light/32x32/apps/org.hydrogenmusic.Hydrogen.svg
    ln -s jdownloader.svg neru-classic-light/32x32/apps/org.jdownloader.JDownloader.svg
    ln -s system-file-manager.svg neru-classic-light/32x32/apps/org.kde.dolphin.svg
    ln -s elisa.svg neru-classic-light/32x32/apps/org.kde.elisa.svg
    ln -s gcompris.svg neru-classic-light/32x32/apps/org.kde.gcompris.svg
    ln -s kalzium.svg neru-classic-light/32x32/apps/org.kde.kalzium.svg
    ln -s kapman.svg neru-classic-light/32x32/apps/org.kde.kapman.svg
    ln -s katomic.svg neru-classic-light/32x32/apps/org.kde.katomic.svg
    ln -s kblocks.svg neru-classic-light/32x32/apps/org.kde.kblocks.svg
    ln -s kbounce.svg neru-classic-light/32x32/apps/org.kde.kbounce.svg
    ln -s kbruch.svg neru-classic-light/32x32/apps/org.kde.kbruch.svg
    ln -s kdenlive.svg neru-classic-light/32x32/apps/org.kde.kdenlive.svg
    ln -s kdiamond.svg neru-classic-light/32x32/apps/org.kde.kdiamond.svg
    ln -s kgeography.svg neru-classic-light/32x32/apps/org.kde.kgeography.svg
    ln -s kgoldrunner.svg neru-classic-light/32x32/apps/org.kde.kgoldrunner.svg
    ln -s khangman.svg neru-classic-light/32x32/apps/org.kde.khangman.svg
    ln -s kigo.svg neru-classic-light/32x32/apps/org.kde.kigo.svg
    ln -s killbots.svg neru-classic-light/32x32/apps/org.kde.killbots.svg
    ln -s kjumpingcube.svg neru-classic-light/32x32/apps/org.kde.kjumpingcube.svg
    ln -s klines.svg neru-classic-light/32x32/apps/org.kde.klines.svg
    ln -s knemo.svg neru-classic-light/32x32/apps/org.kde.knetwalk.svg
    ln -s kolourpaint.svg neru-classic-light/32x32/apps/org.kde.kolourpaint.svg
    ln -s kontact.svg neru-classic-light/32x32/apps/org.kde.kontact.svg
    ln -s krita.svg neru-classic-light/32x32/apps/org.kde.krita.svg
    ln -s ksquares.svg neru-classic-light/32x32/apps/org.kde.ksquares.svg
    ln -s ksudoku.svg neru-classic-light/32x32/apps/org.kde.ksudoku.svg
    ln -s ktouch.svg neru-classic-light/32x32/apps/org.kde.ktouch.svg
    ln -s ktuberling.svg neru-classic-light/32x32/apps/org.kde.ktuberling.svg
    ln -s kubrick.svg neru-classic-light/32x32/apps/org.kde.kubrick.svg
    ln -s kwordquiz.svg neru-classic-light/32x32/apps/org.kde.kwordquiz.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/org.kde.okular.svg
    ln -s palapeli.svg neru-classic-light/32x32/apps/org.kde.palapeli.svg
    ln -s skrooge.svg neru-classic-light/32x32/apps/org.kde.skrooge.svg
    ln -s keepassxc.svg neru-classic-light/32x32/apps/org.keepassxc.KeePassXC.svg
    ln -s kicad.svg neru-classic-light/32x32/apps/org.kicad_pcb.KiCad.svg
    ln -s libreoffice-base.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.base.svg
    ln -s libreoffice-calc.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.calc.svg
    ln -s libreoffice-draw.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.draw.svg
    ln -s libreoffice-impress.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.impress.svg
    ln -s libreoffice-math.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.math.svg
    ln -s libreoffice-main.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.startcenter.svg
    ln -s libreoffice-writer.svg neru-classic-light/32x32/apps/org.libreoffice.LibreOffice.writer.svg
    ln -s manaplus.svg neru-classic-light/32x32/apps/org.manaplus.ManaPlus.svg
    ln -s tiled.svg neru-classic-light/32x32/apps/org.mapeditor.Tiled.svg
    ln -s midori.svg neru-classic-light/32x32/apps/org.midori_browser.Midori.svg
    ln -s mixxx.svg neru-classic-light/32x32/apps/org.mixxx.Mixxx.svg
    ln -s firefox.svg neru-classic-light/32x32/apps/org.mozilla.Firefox.svg
    ln -s firefox-trunk.svg neru-classic-light/32x32/apps/org.mozilla.FirefoxNightly.svg
    ln -s thunderbird.svg neru-classic-light/32x32/apps/org.mozilla.Thunderbird.svg
    ln -s musescore.svg neru-classic-light/32x32/apps/org.musescore.MuseScore.svg
    ln -s nextcloud.svg neru-classic-light/32x32/apps/org.nextcloud.Nextcloud.svg
    ln -s octave.svg neru-classic-light/32x32/apps/org.octave.Octave.svg
    ln -s openshot.svg neru-classic-light/32x32/apps/org.openshot.OpenShot.svg
    ln -s openttd.svg neru-classic-light/32x32/apps/org.openttd.OpenTTD.svg
    ln -s playonlinux.svg neru-classic-light/32x32/apps/org.phoenicis.playonlinux.svg
    ln -s multimedia-photo-viewer.svg neru-classic-light/32x32/apps/org.photoqt.PhotoQt.svg
    ln -s pitivi.svg neru-classic-light/32x32/apps/org.pitivi.Pitivi.svg
    ln -s eternallands.svg neru-classic-light/32x32/apps/org.pjbroad.EternallandsClient.svg
    ln -s document-viewer.svg neru-classic-light/32x32/apps/org.pwmt.zathura.svg
    ln -s qbittorrent.svg neru-classic-light/32x32/apps/org.qbittorrent.qBittorrent.svg
    ln -s QOwnNotes.svg neru-classic-light/32x32/apps/org.qownnotes.QOwnNotes.svg
    ln -s quassel.svg neru-classic-light/32x32/apps/org.quassel_irc.QuasselClient.svg
    ln -s qutebrowser.svg neru-classic-light/32x32/apps/org.qutebrowser.qutebrowser.svg
    ln -s scantailor.svg neru-classic-light/32x32/apps/org.scantailor.ScanTailor.svg
    ln -s stellarium.svg neru-classic-light/32x32/apps/org.stellarium.Stellarium.svg
    ln -s supertux.svg neru-classic-light/32x32/apps/org.supertux.SuperTux-Milestone1.svg
    ln -s synfig_icon.svg neru-classic-light/32x32/apps/org.synfig.SynfigStudio.svg
    ln -s texstudio.svg neru-classic-light/32x32/apps/org.texstudio.TeXstudio.svg
    ln -s minitube.svg neru-classic-light/32x32/apps/org.tordini.flavio.Minitube.svg
    ln -s vlc.svg neru-classic-light/32x32/apps/org.videolan.VLC.svg
    ln -s vim.svg neru-classic-light/32x32/apps/org.vim.Vim.svg
    ln -s widelands.svg neru-classic-light/32x32/apps/org.widelands.Widelands.svg
    ln -s wireshark.svg neru-classic-light/32x32/apps/org.wireshark.Wireshark.svg
    ln -s okteta.svg neru-classic-light/32x32/apps/org.wxhexeditor.wxHexEditor.svg
    ln -s xiphos.svg neru-classic-light/32x32/apps/org.xiphos.Xiphos.svg
    ln -s xonotic.svg neru-classic-light/32x32/apps/org.xonotic.Xonotic.svg
    ln -s gzdoom.svg neru-classic-light/32x32/apps/org.zdoom.GZDoom.svg
    ln -s zeal.svg neru-classic-light/32x32/apps/org.zealdocs.Zeal.svg
    ln -s zim.svg neru-classic-light/32x32/apps/org.zim_wiki.Zim.svg
    ln -s zotero.svg neru-classic-light/32x32/apps/org.zotero.Zotero.svg
    ln -s muon.svg neru-classic-light/32x32/apps/package.svg
    ln -s preferences-activities.svg neru-classic-light/32x32/apps/package_applications.svg
    ln -s accessories-text-editor.svg neru-classic-light/32x32/apps/package_editors.svg
    ln -s plasmagik.svg neru-classic-light/32x32/apps/package_favorite.svg
    ln -s preferences-desktop-gaming.svg neru-classic-light/32x32/apps/package_games.svg
    ln -s fceux.svg neru-classic-light/32x32/apps/package_games_arcade.svg
    ln -s kjumpingcube.svg neru-classic-light/32x32/apps/package_games_board.svg
    ln -s kpatience.svg neru-classic-light/32x32/apps/package_games_card.svg
    ln -s preferences-desktop-emoticons.svg neru-classic-light/32x32/apps/package_toys.svg
    ln -s applications-utilities.svg neru-classic-light/32x32/apps/package_utilities.svg
    ln -s kapman.svg neru-classic-light/32x32/apps/pacman.svg
    ln -s accessories-dictionary.svg neru-classic-light/32x32/apps/palaura.svg
    ln -s disk-utility.svg neru-classic-light/32x32/apps/palimpsest.svg
    ln -s kipi-panorama.svg neru-classic-light/32x32/apps/panini.svg
    ln -s pgadmin.svg neru-classic-light/32x32/apps/pgAdmin4.svg
    ln -s pgadmin.svg neru-classic-light/32x32/apps/pgadmin4.svg
    ln -s tux.svg neru-classic-light/32x32/apps/pinguin.svg
    ln -s plexhometheater.svg neru-classic-light/32x32/apps/plexmediaserver.svg
    ln -s plasmagik.svg neru-classic-light/32x32/apps/preferences-desktop-effects.svg
    ln -s cs-overview.svg neru-classic-light/32x32/apps/preferences-desktop-gestures-screenedges.svg
    ln -s libinput-gestures.svg neru-classic-light/32x32/apps/preferences-desktop-gestures-touch.svg
    ln -s xfce4-taskbar.svg neru-classic-light/32x32/apps/preferences-desktop-plasma-theme.svg
    ln -s applications-interfacedesign.svg neru-classic-light/32x32/apps/preferences-desktop-theme-applications.svg
    ln -s preferences-desktop-theme.svg neru-classic-light/32x32/apps/preferences-desktop-theme-global.svg
    ln -s workspace-switcher-left-bottom.svg neru-classic-light/32x32/apps/preferences-desktop-virtual.svg
    ln -s computerjanitor.svg neru-classic-light/32x32/apps/preferences-system-privacy-housekeeping.svg
    ln -s preferences-system-windows-move.svg neru-classic-light/32x32/apps/preferences-system-tabbox.svg
    ln -s system-users.svg neru-classic-light/32x32/apps/preferences-system-users.svg
    ln -s preferences-system-windows-move.svg neru-classic-light/32x32/apps/preferences-system-windows-effect-flipswitch.svg
    ln -s cups.svg neru-classic-light/32x32/apps/printer1.svg
    ln -s cups.svg neru-classic-light/32x32/apps/printersandfax_q4os_startmenu.svg
    ln -s cups.svg neru-classic-light/32x32/apps/printmgr.svg
    ln -s preferences-system-network.svg neru-classic-light/32x32/apps/proxy.svg
    ln -s pycharm.svg neru-classic-light/32x32/apps/pycharm-community.svg
    ln -s pycharm.svg neru-classic-light/32x32/apps/pycharm-education.svg
    ln -s pycharm.svg neru-classic-light/32x32/apps/pycharm-professional.svg
    ln -s chess.svg neru-classic-light/32x32/apps/pychess.svg
    ln -s kmenuedit.svg neru-classic-light/32x32/apps/q4_findmenu.svg
    ln -s knemo.svg neru-classic-light/32x32/apps/q4_findweb.svg
    ln -s preferences-system-network.svg neru-classic-light/32x32/apps/q4_netcon.svg
    ln -s system-software-update.svg neru-classic-light/32x32/apps/q4os-updatemgr.svg
    ln -s disk-usage-analyzer.svg neru-classic-light/32x32/apps/qdirstat.svg
    ln -s rambox.svg neru-classic-light/32x32/apps/rambox-os.svg
    ln -s preferences-desktop-display.svg neru-classic-light/32x32/apps/randr.svg
    ln -s reddit.svg neru-classic-light/32x32/apps/reddit-is-a-dead-bird.svg
    ln -s rocketchat.svg neru-classic-light/32x32/apps/rocketchat-desktop.svg
    ln -s system-config-samba.svg neru-classic-light/32x32/apps/samba.svg
    ln -s preferences-desktop-gaming.svg neru-classic-light/32x32/apps/sc-controller.svg
    ln -s applets-screenshooter.svg neru-classic-light/32x32/apps/screengrab.svg
    ln -s scribus.svg neru-classic-light/32x32/apps/scribus-trunk.svg
    ln -s stremio.svg neru-classic-light/32x32/apps/smartcode-stremio.svg
    ln -s system-config-samba.svg neru-classic-light/32x32/apps/smb4k.svg
    ln -s krita.svg neru-classic-light/32x32/apps/steam_icon_280680.svg
    ln -s dods.svg neru-classic-light/32x32/apps/steam_icon_30.svg
    ln -s blender.svg neru-classic-light/32x32/apps/steam_icon_365670.svg
    ln -s kolf.svg neru-classic-light/32x32/apps/steam_icon_431240.svg
    ln -s wesnoth.svg neru-classic-light/32x32/apps/steam_icon_599390.svg
    ln -s cs.svg neru-classic-light/32x32/apps/steam_icon_80.svg
    ln -s gnome-twitch.svg neru-classic-light/32x32/apps/streamlink-twitch-gui.svg
    ln -s applications-interfacedesign.svg neru-classic-light/32x32/apps/style.svg
    ln -s sublime-text.svg neru-classic-light/32x32/apps/sublime-text2.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-java-jdk10.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-java-jdk9.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-java-jre10.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-javaws-jdk10.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-javaws-jdk9.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-javaws-jre10.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-jcontrol-jdk10.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-jcontrol-jdk9.svg
    ln -s java.svg neru-classic-light/32x32/apps/sun-jcontrol-jre10.svg
    ln -s software-store.svg neru-classic-light/32x32/apps/swcentre.svg
    ln -s system-switch-user.svg neru-classic-light/32x32/apps/switchuser.svg
    ln -s syncthing-gtk.svg neru-classic-light/32x32/apps/syncthing.svg
    ln -s syncthing-gtk.svg neru-classic-light/32x32/apps/syncthingtray.svg
    ln -s smartgit.svg neru-classic-light/32x32/apps/syntevo-smartgit.svg
    ln -s xfce4-systray.svg neru-classic-light/32x32/apps/systemtray.svg
    ln -s vmpk.svg neru-classic-light/32x32/apps/tdemid.svg
    ln -s preferences-system-network.svg neru-classic-light/32x32/apps/tdenetworkmanager.svg
    ln -s preferences-desktop-screensaver.svg neru-classic-light/32x32/apps/tdescreensaver.svg
    ln -s kdevelop.svg neru-classic-light/32x32/apps/tdevelop.svg
    ln -s cs-login.svg neru-classic-light/32x32/apps/tdmconfig.svg
    ln -s cs-panel.svg neru-classic-light/32x32/apps/tint2.svg
    ln -s tracktion.svg neru-classic-light/32x32/apps/tracktion7.svg
    ln -s com.github.nick92.tranqil.svg neru-classic-light/32x32/apps/tranquil.svg
    ln -s kodi.svg neru-classic-light/32x32/apps/tv.kodi.Kodi.svg
    ln -s ue4editor.svg neru-classic-light/32x32/apps/ubinary.svg
    ln -s skanlite.svg neru-classic-light/32x32/apps/vuescan.svg
    ln -s google-drive.svg neru-classic-light/32x32/apps/web-google-drive.svg
    ln -s wesnoth.svg neru-classic-light/32x32/apps/wesnoth-1.14-icon.svg
    ln -s wesnoth_editor.svg neru-classic-light/32x32/apps/wesnoth-1.14_editor-icon.svg
    ln -s wechat.svg neru-classic-light/32x32/apps/wewechat.svg
    ln -s whatsapp.svg neru-classic-light/32x32/apps/whatsapp-desktop.svg
    ln -s whatsapp.svg neru-classic-light/32x32/apps/whatsapp-nativefier.svg
    ln -s whatsapp.svg neru-classic-light/32x32/apps/whatsdesk.svg
    ln -s wicd.svg neru-classic-light/32x32/apps/wifi-radar.svg
    ln -s preferences-system-windows.svg neru-classic-light/32x32/apps/window_list.svg
    ln -s xorg.svg neru-classic-light/32x32/apps/x.svg
    ln -s xorg.svg neru-classic-light/32x32/apps/xapp.svg
    ln -s accessories-calculator.svg neru-classic-light/32x32/apps/xcalc.svg
    ln -s help-browser.svg neru-classic-light/32x32/apps/xchm-48.svg
    ln -s diodon.svg neru-classic-light/32x32/apps/xclipboard.svg
    ln -s preferences-system-time.svg neru-classic-light/32x32/apps/xclock.svg
    ln -s utilities-terminal.svg neru-classic-light/32x32/apps/xconsole.svg
    ln -s emacs.svg neru-classic-light/32x32/apps/xemacs.svg
    ln -s xournal.svg neru-classic-light/32x32/apps/xournalpp.svg
    ln -s razercommander.svg neru-classic-light/32x32/apps/xyz.z3ntu.razergenie.svg
    ln -s yast.svg neru-classic-light/32x32/apps/yast-control-center.svg
    ln -s preferences-system-network.svg neru-classic-light/32x32/apps/yast-device-tree.svg
    ln -s preferences-desktop-user-password.svg neru-classic-light/32x32/apps/yast-kerberos.svg
    ln -s krfb.svg neru-classic-light/32x32/apps/yast-ldap-server.svg
    ln -s preferences-system-notifications.svg neru-classic-light/32x32/apps/org.xfce.notification.svg
    ln -s accessories-dictionary.svg neru-classic-light/32x32/apps/org.xfce.Dictionary.svg
    
    ln -s application-pkix-cert.svg neru-classic-light/32x32/mimetypes/application-certificate.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/application-vnd.google-apps.document.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/application-vnd.google-apps.spreadsheet.svg
    ln -s text-x-script.svg neru-classic-light/32x32/mimetypes/application-x-kvs.svg
    ln -s audio-x-flac.svg neru-classic-light/32x32/mimetypes/audio-flac.svg
    ln -s application-x-fictionbook.svg neru-classic-light/32x32/mimetypes/djvu.svg
    ln -s application-x-font-ttf.svg neru-classic-light/32x32/mimetypes/font-collection.svg
    ln -s application-x-font-ttf.svg neru-classic-light/32x32/mimetypes/font-otf.svg
    ln -s application-x-font-ttf.svg neru-classic-light/32x32/mimetypes/font-woff.svg
    ln -s application-x-zerosize.svg neru-classic-light/32x32/mimetypes/gnome-fs-regular.svg
    ln -s application-x-iso.svg neru-classic-light/32x32/mimetypes/gnome-mime-application-x-nero-disc-image.svg
    ln -s application-xml.svg neru-classic-light/32x32/mimetypes/gnome-mime-application-x-nero-linux-compilation.svg
    ln -s application-x-krita.svg neru-classic-light/32x32/mimetypes/image-x-krita.svg
    ln -s application-x-iso.svg neru-classic-light/32x32/mimetypes/nero-disc-image.svg
    ln -s application-xml.svg neru-classic-light/32x32/mimetypes/nero-linux-compilation.svg
    ln -s application-vnd.oasis.opendocument.database.svg neru-classic-light/32x32/mimetypes/openoffice4-database.svg
    ln -s application-vnd.oasis.opendocument.graphics.svg neru-classic-light/32x32/mimetypes/openoffice4-drawing-template.svg
    ln -s application-vnd.oasis.opendocument.graphics.svg neru-classic-light/32x32/mimetypes/openoffice4-drawing.svg
    ln -s application-vnd.oasis.opendocument.formula.svg neru-classic-light/32x32/mimetypes/openoffice4-formula.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-master-document.svg
    ln -s application-vnd.oasis.opendocument.database.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-database.svg
    ln -s application-vnd.oasis.opendocument.graphics.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-drawing-template.svg
    ln -s application-vnd.oasis.opendocument.graphics.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-drawing.svg
    ln -s application-vnd.oasis.opendocument.formula.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-formula.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-master-document.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-presentation-template.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-presentation.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-spreadsheet-template.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-spreadsheet.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-text-template.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-text.svg
    ln -s application-x-mswinurl.svg neru-classic-light/32x32/mimetypes/openoffice4-oasis-web-template.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/openoffice4-presentation-template.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/openoffice4-presentation.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/openoffice4-spreadsheet-template.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/openoffice4-spreadsheet.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-text-template.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/openoffice4-text.svg
    ln -s image-x-generic.svg neru-classic-light/32x32/mimetypes/qgis-asc.svg
    ln -s image-x-generic.svg neru-classic-light/32x32/mimetypes/qgis-ddf.svg
    ln -s image-x-generic.svg neru-classic-light/32x32/mimetypes/qgis-dem.svg
    ln -s image-x-generic.svg neru-classic-light/32x32/mimetypes/qgis-dt0.svg
    ln -s image-x-svg+xml.svg neru-classic-light/32x32/mimetypes/qgis-dxf.svg
    ln -s image-x-svg+xml.svg neru-classic-light/32x32/mimetypes/qgis-gml.svg
    ln -s image-x-generic.svg neru-classic-light/32x32/mimetypes/qgis-img.svg
    ln -s text-x-hex.svg neru-classic-light/32x32/mimetypes/qgis-mldata.svg
    ln -s image-x-svg+xml.svg neru-classic-light/32x32/mimetypes/qgis-qlr.svg
    ln -s text-x-qml.svg neru-classic-light/32x32/mimetypes/qgis-qml.svg
    ln -s image-x-svg+xml.svg neru-classic-light/32x32/mimetypes/qgis-shp.svg
    ln -s application-x-sqlite2.svg neru-classic-light/32x32/mimetypes/qgis-sqlite.svg
    ln -s text-x-generic.svg neru-classic-light/32x32/mimetypes/text-x-kvc.svg
    ln -s text-x-python.svg neru-classic-light/32x32/mimetypes/text-x-python3.svg
    ln -s video-x-generic.svg neru-classic-light/32x32/mimetypes/video-mp2t.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/wps-office-doc.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/wps-office-dot.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/wps-office-dps.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/wps-office-dpt.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/wps-office-et.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/wps-office-ett.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/wps-office-pot.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/wps-office-ppt.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/wps-office-wps.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/wps-office-wpt.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/wps-office-xls.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/wps-office-xlt.svg
    ln -s x-office-document.svg neru-classic-light/32x32/mimetypes/x-office-document-template.svg
    ln -s x-office-presentation.svg neru-classic-light/32x32/mimetypes/x-office-presentation-template.svg
    ln -s x-office-spreadsheet.svg neru-classic-light/32x32/mimetypes/x-office-spreadsheet-template.svg
    echo -e "\033[1;35mf\033[1;35mi\033[1;35mx \033[1;34mL\033[1;34mI\033[1;34mN\033[1;34mK\033[0m"
}
link_prepare
